# Generated by Django 4.2.30 on 2026-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
    ]
